name: Publish Mods

on: workflow_dispatch

env:
  PR_AUTHOR: camila314 # {{ github.event.pull_request.user.login }} 

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
      verified: ${{ steps.verify.outputs.verify }}

    steps:
    - uses: actions/checkout@v3
      with:
        repository: camila314/test
        path: repo

    - uses: actions/checkout@v3
      with:
        path: code

    - uses: actions/checkout@v3
      with:
        repository: geode-sdk/index-test
        path: index

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - id: verify
      working-directory: ${{ github.workspace }}/index
      run: python3 ${{ github.workspace }}/code/.github/verify.py $PR_AUTHOR

    - if: ${{ steps.verify.outputs.verify }} == "true"
      id: check
      working-directory: repo
      run: |
        for i in `ls -1d */`; do
          url=`git remote get-url origin`
          branch=`git rev-parse --abbrev-ref HEAD`
          cd ../index
          python3 ../code/.github/publish.py ../repo/$i $PR_AUTHOR $url/raw/$branch/$i
          cd ../repo
        done

    - if ${{ steps.verify.outputs.verify }} == "true"
      run: echo ${{ steps.check.outputs.check }}
      #uses: mshick/add-pr-comment@v2
      #with:
      #  message: ${{ steps.check.outputs.check }}
