name: Publish Mods

on: 
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: echo hi