name: Publish Mods

on: workflow_dispatch

env:
  PR_AUTHOR: camila314 # {{ github.event.pull_request.user.login }} 

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
      verified: ${{ steps.verify.outputs.verify }}

    steps:
    - uses: actions/checkout@v3
      with:
        repository: camila314/test
        path: repo

    - uses: actions/checkout@v3
      with:
        path: code

    - uses: actions/checkout@v3
      with:
        repository: geode-sdk/index-test
        path: index

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - id: verify
      working-directory: ${{ github.workspace }}/index
      run: python3 ${{ github.workspace }}/code/.github/verify.py $PR_AUTHOR

    - id: dirs
      working-directory: repo
      run: echo "::set-output name=dirs::$(ls -d */ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')"

  check:
    needs: initialize
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ${{ fromJson(needs.initialize.outputs.dirs) }}

    steps:

    - id: get-url
      working-directory: repo
      run: git remote get-url origin

    - id: get-branch
      working-directory: repo
      run: git rev-parse --abbrev-ref HEAD

    - if: ${{ needs.initialize.outputs.verified }} == "true"
      run: python3 .github/publish.py ${{ matrix.dir }} $PR_AUTHOR ${{ steps.get-url.outputs.get-url }}/raw/${{ steps.get-url.outputs.get-branch }}/${{ matrix.dir }}
      working-directory: ${{ github.workspace }}

